/**
 * 
 */
package net.sf.reportengine.in;

import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.util.Arrays;

import net.sf.reportengine.core.ReportEngineRuntimeException;
import net.sf.reportengine.core.steps.crosstab.IntermComputedDataList;
import net.sf.reportengine.core.steps.crosstab.IntermComputedTotalsList;
import net.sf.reportengine.core.steps.crosstab.IntermOriginalDataColsList;
import net.sf.reportengine.core.steps.crosstab.IntermOriginalGroupValuesList;
import net.sf.reportengine.core.steps.crosstab.IntermediateReportRow;

import org.apache.log4j.Logger;

/**
 * <p>Intermediate input. (only for internal use)</p> 
 * 
 * <p>Use this input to read temporary files generated by report engine containing 
 * serialized values of the initial input
 * </p>
 * 
 * @author dragos balan (dragos dot balan at gmail dot com)
 * @since 0.4
 */
public class IntermediateCrosstabReportInput extends AbstractReportInput {
	
	/**
	 * the logger
	 */
	private static final Logger logger = Logger.getLogger(IntermediateCrosstabReportInput.class);
	
	/**
	 * input containing serialized intermediate objects
	 */
	private ObjectInputStream intermCtLinesInputStream;
	
	/**
	 * the next unprocessed line
	 */
	private IntermediateReportRow nextRawLine; 
	
	
	/**
	 * 
	 * @param input
	 */
	public IntermediateCrosstabReportInput(InputStream input){
		try {
			this.intermCtLinesInputStream = new ObjectInputStream(input);
		} catch (IOException e) {
			throw new ReportInputException(e); 
		} 
	}
	
	@Override
	public void open(){
		super.open(); 
		if(intermCtLinesInputStream == null) throw new IllegalStateException("Intermediate input stream is null"); 
		nextRawLine = readNextRow(); 
		logger.debug("Intermediate report input opened successfuly"); 
	}

	@Override
	public void close(){
		nextRawLine = null; 
		try {
			intermCtLinesInputStream.close();
		} catch (IOException e) {
			throw new ReportInputException(e); 
		} 
		
		intermCtLinesInputStream = null; 
		super.close(); 
	}
	
	/* (non-Javadoc)
	 * @see net.sf.reportengine.in.AbstractReportInput#nextRow()
	 */
	public Object[] nextRow()  {
		logger.debug("requesting next intermediate row"); 
		Object[] result = null; 
		if(hasMoreRows()){
			result = transformIntermediateCrosstabLine(nextRawLine); 
			
			//prepare the next line
			if(!nextRawLine.isLast()){
				nextRawLine = readNextRow(); 
			}else{
				nextRawLine = null; 
			}
		}
		logger.debug("returning nextRow: "+Arrays.toString(result)); 
		return result; 
	}

	/* (non-Javadoc)
	 * @see net.sf.reportengine.in.AbstractReportInput#hasMoreRows()
	 */
	public boolean hasMoreRows() {
		return nextRawLine != null;
	}

	/**
	 * 
	 * @return
	 */
	private IntermediateReportRow readNextRow(){
		IntermediateReportRow result = null; 
		try {
			result = (IntermediateReportRow)intermCtLinesInputStream.readObject();
		} catch (ClassNotFoundException e) {
			throw new ReportEngineRuntimeException(e); 
		} catch (IOException e) {
			throw new ReportEngineRuntimeException(e);
		} 
		return result; 
	}
	
	/**
	 * the contract is that 
	 * 		result[0] is an instance of IntermGroupValuesList
	 *      result[1] is an instance of OriginalDataValueList
	 * 		result[2] is an instance of IntermComputedDataList
	 * 		result[3] an instance of IntermComputedTotalsList
	 * @param intermRow
	 * @return
	 */
	private Object[] transformIntermediateCrosstabLine(IntermediateReportRow intermRow){
		if(logger.isDebugEnabled())logger.debug("transforming line: "+intermRow);
		Object[] result = null; 
		
		if(intermRow != null){
			result = new Object[4];
			IntermOriginalGroupValuesList intermGroupValues = intermRow.getIntermGroupValuesList(); 
			if(intermGroupValues != null){
				result[0] = intermGroupValues; 
			}
			
			IntermOriginalDataColsList intermOrigDataColValues = intermRow.getIntermOriginalDataValuesList(); 
			if(intermOrigDataColValues != null){
				result[1] = intermOrigDataColValues; 
			}
			
			IntermComputedDataList intermDataList = intermRow.getIntermComputedDataList(); 
			if(intermDataList != null){
				result[2] = intermDataList; 
			}
			
			IntermComputedTotalsList intermTotals = intermRow.getIntermComputedTotalsList(); 
			if(intermTotals !=  null){
				result[3] = intermTotals; 
			}
		}
		return result; 
	}
}